all:
	g++ -Wall -g RedBlackTree.cpp RedBlackTreeTests.cpp -o rbt
	g++ -Wall -g RedBlackTree.cpp RedBlackTreeTestsFirstStep.cpp -o rbtfs
 
runrbt:
	./rbt
runrbtfs:
	./rbtfs

check:
	valgrind --leak-check=full ./rbt
	valgrind --leak-check=full ./rbtfs
